### ISSUE TITLE
Unclear Usage Instructions

### ISSUE THREAD

**Issue by giladturok** [stan-dev/posteriordb-python#4]
Clarify usage instructions when using (local) `PosteriorDabase`.

The README has usage instructions that explain how to use the (local) `PosteriorDatabase` class. However, it does not clearly state that one must first _clone_ the original PosteriorDB GitHub repo from https://github.com/stan-dev/posteriordb. Thus naively installing `pip install posteriordb` and running the example with `PosteriorDatabase` fails.

This is especially confusing since the example states the default path is set to  `posteriordb/posterior_database`. However, this exact directory structure appears in both `posteriordb` and the interface `posteriordb-python`.

It would be especially helpful if the instructions clarified when discussing `posteriordb-python` and when discussing `posteriordb`.

Screenshot of the confusing instructions:
<img width="993" alt="Screenshot 2024-09-25 at 3 32 48 PM" src="https://github.com/user-attachments/assets/c8073ae4-5c40-4ad5-84ac-cc94025896b0">

**Comment by bob-carpenter** [comment]
Thanks for posting the issue, @gil2rok.  Do you want to take a stab at fixing the instructions and submitting a PR?

**Comment by giladturok** [comment]
Sure!
